// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	UserName     string
	PasswordHash string
}

type UserAction struct {
	ID        int32
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
}
