// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, user_name, password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, user_name, password_hash
`

type CreateUserParams struct {
	ID           pgtype.UUID
	UserName     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.UserName, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.UserName, &i.PasswordHash)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, user_name, password_hash FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.UserName, &i.PasswordHash)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, password_hash FROM users
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(&i.ID, &i.UserName, &i.PasswordHash)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, password_hash FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.UserName, &i.PasswordHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    user_name = $2,
    password_hash = $3
WHERE id = $1
RETURNING id, user_name, password_hash
`

type UpdateUserParams struct {
	ID           pgtype.UUID
	UserName     string
	PasswordHash string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.UserName, arg.PasswordHash)
	return err
}
